### ISSUE TITLE
Add of periodical automatic refresh of temperature & humidity

### ISSUE THREAD

**Issue by kellermeister76** [lucacri/homebridge-http-temperature-humidity#13]
with the actual Version, the values must be refreshed Manual in the app elgato or idevice.
please make the Extension that the values of temperature and humidity refresh automaticly 
every each time.
Thanks.

**Comment by lucacri** [comment]
Hi, unfortunately that's a problem with the elgato app. This tool gives the temperature to homebridge when requested (as per homekit specification), and it has no way to "feed" the updated temperature/humidity to homebridge. It's homebridge's job to request the data
