### ISSUE TITLE
Temperature below 0degrees

### ISSUE THREAD

**Issue by matej-cupka** [lucacri/homebridge-http-temperature-humidity#14]
Plugin not working if temperature went below 0degrees, would be nice to see fix. Otherwise it's great plugin.

**Comment by jubudu** [comment]
Hello, 
weather has become cold: I am facing the same problem with temperature below 0 degrees. DHT gives temperature -1 and home kit reports "no answer".
Thanks for fixing this!

**Comment by oskarrn93** [comment]
Hi,

I'm kind of new to Github and I don't know how to add code proposals.

I solved it by adding the following line to temperatureService: .setProps({minValue: -100, maxValue: 100})

So it will look like this on row 91 to 94.

temperatureService
                .getCharacteristic(Characteristic.CurrentTemperature)
                .setProps({minValue: -100, maxValue: 100})
                .on('get', this.getState.bind(this));

**Comment by lucacri** [comment]
Fixed in 0.0.15
