### ISSUE TITLE
Arduino Sensor

### ISSUE THREAD

**Issue by FabioMarquesim** [lucacri/homebridge-http-temperature-humidity#20]
Hello man, 
Today i use the raspberry pi with homebridge and arduino with sensors, how i can send the temperature and humidity by http to homebridge on raspberry pi?

**Comment by lucacri** [comment]
This package needs an external URL that replies with a JSON of the temperature/humidity. I'm sure you can do the same with a raspberry pi and nginx, but it's out of the scope of this package

**Comment by FabioMarquesim** [comment]
How should I handle the request?

**Comment by lucacri** [comment]
The package makes a GET request to the endpoints described in the config file.

Thank you,
Luca

**Comment by FabioMarquesim** [comment]
Thanks
