### ISSUE TITLE
Still "no reply" with negative temperature

### ISSUE THREAD

**Issue by Giorgiofox** [lucacri/homebridge-http-temperature-humidity#27]
Hello,
with " [12/17/2016, 6:36:01 PM] [Esterno] { temperature: -0.1, humidity: 92 }" still have "no reply" from sensor.

I have manually updated /usr/local/lib/node_modules/homebridge-httptemperaturehumidit/index.js

Maybe my update procedure is wrong?

**Comment by lucacri** [comment]
Did you try the new 0.0.15 version? in that one, I merged a PR that should have fixed the issue

**Comment by Giorgiofox** [comment]
How I can do to update it?
sudo npm update?
I've manually copied the code of the index.js file. 

Edit: I've tried, now I have only to wait negative temperature ;)

**Comment by Giorgiofox** [comment]
I can confirm that  still having problem with negative temperature

**Comment by devinjparsons** [comment]
@lucacri you seemed to have changed the humidity service to allow for a larger min value, but i dont see a change to the temperature service.

I changed the temperature service to be like this and it now works with negative temps
`temperatureService
                .getCharacteristic(Characteristic.CurrentTemperature)
                .setProps({minValue: -100, maxValue: 100})
                .on('get', this.getState.bind(this));`

Formatting is a little off but just insert the setProps line into the temperatureService call

**Comment by lucacri** [comment]
Hey, I am not using this because I switched to a mosquitto system. If you want, send a PR and I'll merge it

**Comment by lucacri** [comment]
Fixed by version 0.0.16 (#29)
