### ISSUE TITLE
max humidity 200

### ISSUE THREAD

**Issue by b2un0** [lucacri/homebridge-http-temperature-humidity#34]
you set the max humidity to 200 (why?).
my json web service from DHT22 Sensor response 34 for humidity, but the Apple Home App says 17 (34 / 2).

if i change the max value from 200 to 100 everything shows correct in the apple home app.

should fix this?

https://github.com/lucacri/homebridge-http-temperature-humidity/blob/d7aba7d6411161d5c68020e6a77fa530dff3660c/index.js#L106

**Comment by KiLLeRRaT** [comment]
I'm having the same issue here.
