### ISSUE TITLE
example for "weather" page neaded

### ISSUE THREAD

**Issue by OllySchulte** [lucacri/homebridge-http-temperature-humidity#5]
Can you give me an example how the /weather page (given in the url-parameter) has to look like? I would like to create my own values and send them to homebridge using this module.... thank you :)

**Comment by lucacri** [comment]
Hi!

The /weather endpoint responds with a json that looks like this:

``` javascript
{
"temperature": 25.8,
"humidity": 38
}
```

**Comment by OllySchulte** [comment]
Hi,
thank you. That works :-)

When value is set there is a string containing a <buffer first - that results in an error in the eve-app:

[Wohnzimmer Klima] HTTP power function succeeded!
[Wohnzimmer Klima] <Buffer 7b 22 74 65 6d 70 65 72 61 74 75 72 65 22 3a 20 32 33 2e 34 2c 22 68 75 6d 69 64 69 74 79 22 3a 20 34 39 2e 35 7d 20>
[Wohnzimmer Klima] { temperature: 23.4, humidity: 49.5 }

![fotobox1](https://cloud.githubusercontent.com/assets/13035174/13314915/fa649190-dba7-11e5-804e-41a24fa6a6b5.jpg)

![img_7182](https://cloud.githubusercontent.com/assets/13035174/13314974/4ca67c3e-dba8-11e5-944a-e15fb0257f6f.PNG)

Can I disable the buffer string?

**Comment by lucacri** [comment]
Sorry, i didn't see the reply you posted! I assume you can remove that string. Want to test it and report back?

**Comment by OllySchulte** [comment]
No problem. Yes, if you can change this problem I can test it again :)

Am 23.03.2016 um 17:06 schrieb Luca Critelli:
