### ISSUE TITLE
Updating of humidity is not working

### ISSUE THREAD

**Issue by ZaubererMD** [lucacri/homebridge-http-temperature-humidity#6]
I tried this and at first it seemed to work fine, than I noticed that the humidity is not updated in my app on iOS. It always appeared to show some value for a split-second at refresh and then went back to zero.

I fixed this by adding the following line under `this.temperature = Number( info.temperature );`:

`this.humidity = Number( info.humidity);`

**Comment by lucacri** [comment]
Can you submit a PR?

**Comment by ZaubererMD** [comment]
Actually I'm a GitHub newbie and have no idea how to do that... I just know how to use git in command line.

I imagine it works like this, correct me if I'm wrong:
1. fork the project
2. clone it to my pc
3. do the change
4. commit
5. push back to my fork on github
6. create pull request

Is that correct or do I have to do something else?

**Comment by lucacri** [comment]
Yep! That sounds like all the steps ;-)

Thank you,
Luca

**Comment by ZaubererMD** [comment]
Ok I submitted a pr. Hope everything is fine, if not just let me know.
