### ISSUE TITLE
Project does not indicate what type of hardware is supported

### ISSUE THREAD

**Issue by deftdawg** [lucacri/homebridge-http-temperature-humidity#9]
I'd love to use this plugin to get the temperature and humidity in rooms around my house, the problem is nowhere does this project mention what type of hardware it works with.

**Comment by Ricardo1980** [comment]
The doc says "I used a simple NodeMCU board and a DHT11 (or DHT22)."

Is it difficult to do that?

**Comment by deftdawg** [comment]
Ah, cool... the readme was updated shortly after I opened this issue with this commit

https://github.com/lucacri/homebridge-http-temperature-humidity/commit/15cd7e1945a3f9998995b60a2756158ce6a86d55
